# 2018-03-29 Fixing IndexError: list index out of range from sys.argv 

So when runing my certs scanner script I was getting IndexError: list index out of range when not specifying an argument
upon calling the script.
```python
$ ./certs_scanner.py 
Traceback (most recent call last):
  File "./certs_scanner.py", line 19, in <module>
    if (sys.argv[1] == "init"):
IndexError: list index out of range
```

I didn't have time to fix this the other day.   Could have tackled this one of two ways, either with Try and Except and catch IndexError

Or the way I approached it was checking for the number of command line arguments.    When the script is called with no additional 
command line arguments sys.argv list contains only one element, the name of the script.

So added this simple if statement to resolve:
```python
if len(sys.argv) < 2:
    print("USAGE: certs_scanner.py init|scan")
    sys.exit()
```
